POST http://localhost:3000/records
Content-Type: application/json

{
    "type": "income",
    "amountString": "10",
    "toAccountId": "257de1ac-b7bc-4415-a2be-d2d4beec976c",
    "categoryId": "8c071d97-479c-4685-892d-7b5c0330dc89",
    "notes": "Trial"
}