POST http://localhost:3000/records
Content-Type: application/json

{
    "type": "income",
    "amountString": "10",
    "toAccountId": "1198d07d-3302-4461-959a-f7e780205a8b",
    "categoryId": "1015fc96-c4d1-47df-8468-6fbb280e0943",
    "notes": "Trial"
}