POST http://localhost:3000/records
Content-Type: application/json

{
    "type": "income",
    "amountString": "10",
    "toAccountId": "1e6fd507-fe1b-409c-8ca9-d8683e5a05f1",
    "categoryId": "3c467b2c-d8d9-495a-b652-5b3899c6e57d",
    "notes": "Trial"
}